jobs:
  include:
  - stage: "Test"
    install: ci/docker-setup.sh
    script: ci/docker-run.sh
    env:
    - SNAPSHOT=true ELASTIC_STACK_VERSION=8.0.0-SNAPSHOT
    - SNAPSHOT=true ELASTIC_STACK_VERSION=7.6.0-SNAPSHOT
    - ELASTIC_STACK_VERSION=7.5.1
    - ELASTIC_STACK_VERSION=6.8.6
    - ELASTIC_STACK_VERSION=5.6.16
  - stage: "Deploy"
    script: skip
    language: generic
    if: branch = master AND type = push
    env: ELASTIC_STACK_VERSION=7.5.1
    deploy:
      provider: script
      script: ci/docker-publish.sh
