jobs:
  include:
    - env: SNAPSHOT=true ELASTIC_STACK_VERSION=8.0.0-SNAPSHOT
    - env: SNAPSHOT=true ELASTIC_STACK_VERSION=7.6.0-SNAPSHOT
    - env: ELASTIC_STACK_VERSION=7.5.1
    - env: ELASTIC_STACK_VERSION=6.8.6
    - env: ELASTIC_STACK_VERSION=5.6.16
    - stage: "Deploy"
      script: skip
      language: generic
      if: branch = master AND type = push
      deploy:
        provider: script
        script: ci/docker-publish.sh
  fast_finish: true
