jobs:
  include:
  - env: SNAPSHOT=true ELASTIC_STACK_VERSION=8.x
  - env: SNAPSHOT=true ELASTIC_STACK_VERSION=7.x
  - env: ELASTIC_STACK_VERSION=7.x
  - env: SNAPSHOT=true ELASTIC_STACK_VERSION=6.x
  - env: ELASTIC_STACK_VERSION=6.x
  - env: ELASTIC_STACK_VERSION=5.x
  fast_finish: true
